### ISSUE TITLE
Create new 2.10.0 Release

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#237]
# Situation

IMHO, we should create a new release with all the new additions. :tada: :smile: 

# Proposal

We should finish/clarify the following issues before we create the release:

* [x] ~#229: "Deprecate module level functions"~
* [x] ~#235: "Shift focus on semver.VersionInfo.* functions"~
* [x] ~#236: "Deprecate semver.match?"~
* [x] ~#222 : "First implementation of next_version"~
* [x] ~#138: "Add `__getitem__` method"~

# Questions

Should we create a new 2.9.2 release or 2.10.0? The latter seems to be more appropriate according to the [semver specification item 7](https://semver.org/#spec-item-7) (emphasize by me):

  > Minor version Y (x.Y.z | x > 0) MUST be incremented if **new, backwards compatible functionality is introduced to the public API**. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.

@python-semver/reviewers @gsakkis: Opinions?

----

**Update 2020-04-25**: Add pr #222 to the list.

**Comment by scls19fr** [comment]
Ok let's publish 2.10.0

**Comment by tomschr** [comment]
A first RC1 is available at TestPyPI: https://test.pypi.org/project/semver/2.10.0rc1/
