### ISSUE TITLE
Create 2.11.0 Release

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#288]
The new release contains:

* [x] #274 / #275 String Types Py2 vs. Py3 compatibility
* [x] #277 Turn VersionInfo.parse into classmethod to allow subclasses
* [x] #286 Add author and update changelog for #276/#277
