### ISSUE TITLE
Create semver 3.0.0-dev3

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#315]
# Situation

As 3.0.0-dev.2 was just released, we should think about to coordinate the next development release.

# Suggested Plan

Some ideas for this release:

* [ ] ~#248: Define own hierarchy of exceptions?~
* [ ] ~#303: Rethinking `__init__` of Version class?~
* [x] #309: Rework some "private" functions in `semver.version`?
* [x] ~#316 Should `_comparator` return `NotImplemented` instead of raising `TypeError`?~

**Comment by josefkorbel** [comment]
I've just found this issue while dealing with development pypi packages versioning, so I read PEP440 (https://www.python.org/dev/peps/pep-0440/) and according to that the semantic version of `3.0.0.-dev.2` is actually not valid if I am not mistaken, as it should be `3.0-dev2`.

**Comment by tomschr** [comment]
Thanks Josef, much appreciated your report.

Well, seems semver and PEP440 are only partly compatible. Semver allows to define a patch part, whereas PEP440 does not. There are different approaches in the wild how to deal with version information.

Apart from that, PEP440 has been assigned the type "_Informational_". According to [PEP001](https://www.python.org/dev/peps/pep-0001/#id40), this type is defined as (emphasize by me):

> "An Informational PEP describes a Python design issue, or provides general guidelines or information to the Python community, but does not propose a new feature. Informational PEPs do not necessarily represent a Python community consensus or recommendation, so users and **implementors are free to ignore Informational PEPs** or follow their advice."

A lot of libraries do that and follow a different approach. :wink: 

For this reason, I would tend to follow what's written in the description.
